SHELL = /bin/sh


all: data_compile data_dict

data_compile:
	./data_compile.sh
data_dict:
	./data_dict.sh

clean:
	rm -f ../../../../../data_bin/sl/morph/hin/*.c 
	rm -f ../../../../../data_bin/sl/morph/hin/const.h 
	rm -f ../../../../../data_bin/sl/morph/hin/dict_final 
	rm -f ../../../../../data_bin/sl/morph/hin/pdgm_offset_info
	rm -f ../../../../../data_bin/sl/morph/hin/suff
	rm -f ../../../../../data_bin/sl/morph/hin/uword.dbm

	
