Adj_case_e
aneka
anekoM/anekoz
anekoM/anekoz
kaI
kaiyoM/kaiyoz/kaioz/kaioM
kaiyoM/kaiyoz/kaioz/kaioM
bIsa
bIsiyoM/bIsiyoz/bIsioz/bIsioM
bIsiyoM/bIsiyoz/bIsioz/bIsioM
ikkAnave
ikkAnaveoM/ikkAnaveoz/ikkAnavevoz/ikkAnavevoM
ikkAnaveoM/ikkAnaveoz/ikkAnavevoz/ikkAnavevoM
xonoM
xonoM/xonoz
xonoM/xonoz
saba
saBI
saBI
